// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://grmffahduigdchaeextq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdybWZmYWhkdWlnZGNoYWVleHRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExNjg3MzUsImV4cCI6MjA1Njc0NDczNX0.adDbqT_rD0UXO8TiEhYvxw-r0DHffblM_DFJ_ePQSRs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);